apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: shwecherry-com-tls
spec:
  secretName: shwecherry-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: shwecherry.com
  dnsNames:
    - shwecherry.com
    - www.shwecherry.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - shwecherry.com
          - www.shwecherry.com